# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b5152d1a5f6a0029dee69aa3245d0c5e6344ae985c14d2565724b95bf2670c676c8c9b055050c3bd3b53b8d9e725e2a8527bdc105c4591679f14e865428b5e2

test:
  secret_key_base: a9b6300c7b3d93145c741aa8eaf6032d339953f28b06ef6dbdfcf02a7989b9275935d918951c5de398f26f9198514bbd10651db2150b46ed1c304e4fb59550d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
